gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    ttl: 2592000
    single_use: true

    cookie:
        enabled: true
        same_site: strict               # default value (указание будут ли (и когда) файлы куки отправляться с межсайтовыми запросами)
        path: /api/token                      # default value (путь, который должен быть в запрашиваемом урле)
        domain: 127.0.0.1           # default value (какие хосты могут принимать куки)
        http_only: true              # default value
        secure: false                 # default value
        remove_token_from_body: true # default value