nelmio_cors:
    defaults:
        allow_credentials: true
        origin_regex: false
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
        allow_headers: ['*']
        expose_headers: []
        max_age: 3600
    paths:
        # тут можно переопределить или дополнительно указать настройки для роутов
