controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_token_get:
    path: /api/token/get

api_refresh_token:
    path: /api/token/refresh

api_token_invalidate:
    path: /api/token/invalidate